# -*- coding: utf-8 -*-
"""Stock_Portfolio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eu8N9F8Nf_1ELDMAB2ntoS7dWiShgXF5
"""

import pandas as pd
import numpy as np
import requests
import io
import pandas_datareader as web

from google.colab import files
uploaded = files.upload()

ticker = pd.read_csv(io.BytesIO(uploaded['nasdaq.csv']))['Symbol']

df = pd.DataFrame
for symbol in ticker:
    df = web.DataReader(symbol, "yahoo", "2013-01-01", "2020-12-29")